name: CI – Build and Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: dotnet build
      - name: Run tests
        run: dotnet test
