name: CI – Build Only

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ajusta si usas otra versión

      # (Opcional) Mostrar .csproj encontrados para depurar rutas
      - name: List csproj files
        run: |
          pwd
          find . -maxdepth 2 -name "*.csproj" -print

      - name: Restore
        run: dotnet restore ./ListaDeCompras.csproj

      - name: Build
        run: dotnet build ./ListaDeCompras.csproj --configuration Release --no-restore
